"""
Prompt templates used across the application.
"""

# Reusable prompt template string with placeholders
PROMPT_TEMPLATE = (
    "# Prompt for {{scene_title}}\n"
    "\n"
    "## Task Description\n"
    "Generate content based on the following scene description:\n"
    "\n"
    "{{scene_content}}\n"
    "\n"
    "## Instructions\n"
    "- Follow the structure and key elements from the scene description\n"
    "- Maintain consistency with the overall story tone and style\n"
    "- Focus on the specific elements mentioned in this scene\n"
    "- Ensure the generated content aligns with the project's narrative direction\n"
    "\n"
    "## Output Format\n"
    "Provide your response in markdown format.\n"
)

# Additional reusable prompt templates for future expansion

IMAGE_PROMPT_TEMPLATE = (
    "# Image Prompt for {{scene_title}}\n"
    "\n"
    "## Scene Description\n"
    "{{scene_content}}\n"
    "\n"
    "## Visual Style\n"
    "{{visual_style}}\n"
    "\n"
    "## Composition\n"
    "{{composition}}\n"
    "\n"
    "## Camera Settings\n"
    "{{camera}}\n"
    "\n"
    "## Lighting\n"
    "{{lighting}}\n"
    "\n"
    "## Quality\n"
    "{{quality}}\n"
    "\n"
    "## Negative Prompt\n"
    "{{negative_prompt}}\n"
)

NARRATION_PROMPT_TEMPLATE = (
    "# Narration Prompt for {{scene_title}}\n"
    "\n"
    "## Scene Description\n"
    "{{scene_content}}\n"
    "\n"
    "## Narration Style\n"
    "{{narration_style}}\n"
    "\n"
    "## Tone\n"
    "{{tone}}\n"
    "\n"
    "## Pacing\n"
    "{{pacing}}\n"
    "\n"
    "## Voice Style\n"
    "{{voice_style}}\n"
    "\n"
    "## Target Duration\n"
    "{{target_duration}}\n"
    "\n"
    "## Delivery Notes\n"
    "{{delivery_notes}}\n"
)
