import os
from pathlib import Path


class StoryService:
    """Service for managing project stories."""
    
    def __init__(self, projects_dir: str = "workspace/projects"):
        self.projects_dir = projects_dir
    
    def get_story_path(self, slug: str) -> str:
        """Get the path to a story file for a given project slug."""
        return os.path.join(self.projects_dir, slug, "story", "story.md")
    
    def get_expanded_story_path(self, slug: str) -> str:
        """Get the path to an expanded story file for a given project slug."""
        return os.path.join(self.projects_dir, slug, "story", "expanded_story.md")
    
    def read_story(self, slug: str) -> str:
        """
        Read the story content for a given project slug.
        
        Args:
            slug (str): The project slug
            
        Returns:
            str: The story content or empty string if file doesn't exist
        """
        story_path = self.get_story_path(slug)
        if os.path.exists(story_path):
            with open(story_path, 'r', encoding='utf-8') as f:
                return f.read()
        return ""
    
    def read_expanded_story(self, slug: str) -> str:
        """
        Read the expanded story content for a given project slug.
        
        Args:
            slug (str): The project slug
            
        Returns:
            str: The expanded story content or empty string if file doesn't exist
        """
        expanded_path = self.get_expanded_story_path(slug)
        if os.path.exists(expanded_path):
            with open(expanded_path, 'r', encoding='utf-8') as f:
                return f.read()
        return ""
    
    def save_story(self, slug: str, content: str) -> bool:
        """
        Save story content for a given project slug.
        
        Args:
            slug (str): The project slug
            content (str): The story content to save
            
        Returns:
            bool: True if successful, False otherwise
        """
        story_path = self.get_story_path(slug)
        try:
            # Ensure the directory exists
            Path(story_path).parent.mkdir(parents=True, exist_ok=True)
            
            with open(story_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True
        except Exception:
            return False
            
    def save_expanded_story(self, slug: str, content: str) -> bool:
        """
        Save expanded story content for a given project slug.
        
        Args:
            slug (str): The project slug
            content (str): The expanded story content to save
            
        Returns:
            bool: True if successful, False otherwise
        """
        expanded_path = self.get_expanded_story_path(slug)
        try:
            # Ensure the directory exists
            Path(expanded_path).parent.mkdir(parents=True, exist_ok=True)
            
            with open(expanded_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True
        except Exception:
            return False
            
    def generate_mock_story(self, project_name):
        """Generate deterministic placeholder story content for a given project name."""
        return f"# {project_name}\n\nThis is a mock story generated for the project '{project_name}'.\n\nThe story contains placeholders that would normally be generated by an AI model.\n\n## Story Elements\n\n- Character: Placeholder Hero\n- Setting: Unknown Location\n- Plot: Adventure awaits\n\nThis is placeholder content that will be replaced with actual AI-generated content in future implementations."
